// @anas/shared — shared types, schemas, and validators

export const VERSION = '0.3.1'

// Access / permissions schemas (layered editor — Epic 4.7.2)
export {
  AccessEntry,
  AccessLevel,
  DatasetAccess,
  SetAccessRequest,
} from './schemas/access.js'

// AHR schemas (Epic 11 + AHR — ANAS Hybrid RAID)
export {
  AhrArray,
  AhrArrayMember,
  AhrArraySync,
  AhrCapacity,
  AhrCreateRequest,
  AhrCreateSnapshotRequest,
  AhrDisk,
  AhrDiskPartition,
  AhrDiskRole,
  AhrExpandRequest,
  AhrExpansionIntent,
  AhrExpansionState,
  AhrExpansionStep,
  AhrExpansionStepKind,
  AhrExpansionTrigger,
  AhrLayoutPreview,
  AhrLayoutPreviewRequest,
  AhrMemberState,
  AhrMountpointRequest,
  AhrPool,
  AhrPoolState,
  AhrPreviewBand,
  AhrReplacePair,
  AhrReplaceRequest,
  AhrScrubFinding,
  AhrScrubResult,
  AhrScrubStripe,
  AhrSnapshot,
  AhrSnapshotName,
  AhrSpareRequest,
  AhrStepStatus,
  AhrSyncAction,
  AhrType,
  ArrayLevel,
  ArrayState,
} from './schemas/ahr.js'

// API envelope schemas
export {
  ApiError,
  ConfirmHeader,
  dataResponse,
  ErrorCode,
  RequestHeaders,
} from './schemas/api.js'

// Backup schemas (Epic 16 — PBS file backup)
export {
  ArchivePath,
  archiveSpecType,
  BACKUP_SKIP_EXIT_CODE,
  BACKUP_SKIPPED_OFF_WEEK,
  BACKUP_WEEKDAYS,
  BackupArchive,
  BackupArchiveConsistency,
  BackupArchiveKind,
  BackupArchiveName,
  BackupAuthType,
  BackupBrowseEntry,
  BackupBrowseEntryType,
  BackupBrowseRequest,
  BackupBrowseResult,
  BackupCadence,
  BackupCadenceKind,
  BackupConsistency,
  BackupExpandedArchive,
  BackupFilesRestoreRequest,
  BackupFilesRestoreResult,
  BackupGroup,
  BackupGroupList,
  BackupImageRestoreNewLunTarget,
  BackupImageRestoreRequest,
  BackupImageRestoreResult,
  BackupIncludeNested,
  BackupLunRef,
  BackupLunSource,
  BackupLunSourceKind,
  BackupLunSourceList,
  BackupName,
  BackupNestedEntry,
  BackupNestedKind,
  BackupNestedPreviewRequest,
  BackupNestedPreviewResponse,
  BackupNestedScan,
  BackupNewLunBacking,
  BackupNotifyMode,
  BackupPrunePreviewRequest,
  BackupPrunePreviewResponse,
  BackupPruneResult,
  BackupPruneSnapshot,
  BackupPruneVerdict,
  BackupRateLimit,
  BackupReadVerdict,
  BackupRecentRun,
  BackupRepo,
  BackupRepoRef,
  BackupRepoRegistry,
  BackupRepoResponse,
  BackupRepoSource,
  BackupRepoTestRequest,
  BackupRepoTestResult,
  BackupRepoWrite,
  BackupRestoreOptions,
  BackupRestoreProgress,
  BackupRestoreRequest,
  BackupRestoreStatus,
  BackupRestoreTarget,
  BackupRestoreTargetMode,
  BackupRetention,
  BackupRunRequest,
  BackupRunResult,
  BackupSnapshot,
  BackupSnapshotBackend,
  BackupSnapshotFile,
  BackupSnapshotFileKind,

  BackupSnapshotList,
  BackupSnapshotPath,
  BackupTask,
  BackupTaskDetail,
  BackupTaskEntry,
  BackupTaskKind,
  BackupTaskRequest,
  BackupTaskView,
  BackupTimeOfDay,
  BackupTransientSnapshot,
  BackupWeekday,
  BackupWeekParity,
  BLOCK_ARCHIVE_NAME,
  cadenceToOnCalendar,
  ChangeDetectionMode,
  classifyArchiveFile,
  composeGroupId,
  composeSnapshotId,
  deriveArchiveName,
  effectiveArchiveKind,
  effectiveIncludeNested,
  effectiveTaskKind,
  expandedArchiveName,
  groupOfSnapshotId,
  hasRetentionKeeps,
  IMG_ARCHIVE_SUFFIX,
  isBrowsableArchive,
  isPathWithin,
  lunBackupId,
  MAX_RESTORE_SELECTIONS,
  nestedIncluded,
  parseSnapshotId,
  PVE_REPO_PREFIX,
  restorePatternFor,
  restorePatternsFor,
  snapshotTimeIso,
  UpsertBackupRepoRequest,
} from './schemas/backup.js'

// Common validators
export {
  AbsolutePath,
  DatasetPath,
  DevicePath,
  DiskId,
  fmtBytes,
  hasControlChars,
  ISODateTime,
  NotifyMode,
  PoolName,
  ShareName,
  SingleLine,
  SnapshotName,
  UUID,
} from './schemas/common.js'

// Dashboard schemas (Epic 2)
export {
  AhrBandBrief,
  AhrBandMemberBrief,
  AhrBandTelemetry,
  AhrPoolBrief,
  AhrPoolTelemetry,
  ArcTelemetry,
  DashboardWarning,
  DiskHealthCounts,
  DiskTelemetry,
  IoStats,
  JobBrief,
  NetInterface,
  NetTelemetry,
  PoolStatusBrief,
  PoolTelemetry,
  ShareStatusBrief,
  StatusSummary,
  Telemetry,
  VdevTelemetry,
} from './schemas/dashboard.js'

// Dataset schemas
export {
  AssociatedShare,
  CreateDatasetRequest,
  Dataset,
  DatasetDetail,
  DatasetListDefaults,
  DatasetProperties,
  DatasetType,
  MountpointPermissions,
  RecordSize,
  SetPermissionsRequest,
  UpdateDatasetPropertiesRequest,
  VolBlockSize,
  VolSize,
} from './schemas/datasets.js'

// Disk schemas
export {
  Disk,
  DiskHandsOffTag,
  DiskHealthStatus,
  DiskPartition,
  DiskUsageStatus,
  isComposableDisk,
  SmartAttribute,
  SmartData,
  SmartHealth,
} from './schemas/disks.js'

// Filesystem browse (read-only UI support — Epic 16.9)
export {
  FsBrowseQuery,
  FsBrowseResult,
  FsEntryType,
} from './schemas/fs.js'

// Identity schemas (share users & groups — Epic 8)
export {
  CreateGroupRequest,
  CreateShareUserRequest,
  IdentityName,
  LookupName,
  SetSmbPasswordRequest,
  SetUserEnabledRequest,
  ShareGroup,
  ShareUser,
  SystemGroup,
  SystemUser,
  UpdateGroupMembersRequest,
} from './schemas/identity.js'

// iSCSI schemas (iscsi epic — LIO block storage, target side only)
export {
  aclAuthRequirement,
  aclSatisfiesAuth,
  AddIscsiLunRequest,
  ANAS_IQN_AUTHORITY_LABEL,
  ANAS_IQN_FALLBACK_NODE_LABEL,
  anasIqn,
  anasIqnAuthority,
  anasTargetName,
  CreateIscsiTargetRequest,
  DeleteIscsiLunQuery,
  emptyAclsSentence,
  ipFamily,
  isAnasIqn,
  ISCSI_BACKSTORE_PLUGINS,
  ISCSI_CHAP_SECRET_MAX_BYTES,
  ISCSI_CHAP_SECRET_MIN_BYTES,
  ISCSI_DEFAULT_PORT,
  ISCSI_LUN_NAME_INQUIRY_CHARS,
  IscsiAcl,
  IscsiAclCredentialState,
  IscsiAclRequest,
  IscsiAuthMode,
  IscsiAvailability,
  IscsiBlockSize,
  IscsiChapSecret,
  IscsiChapUserid,
  IscsiClaim,
  IscsiClaimList,
  IscsiDisabledTarget,
  IscsiFirewallAdvisory,
  IscsiForeignChange,
  IscsiForeignChangeKind,
  IscsiHealth,
  IscsiHeldByLun,
  IscsiIqn,
  IscsiLun,
  IscsiLunAttributes,
  IscsiLunCreateKind,
  IscsiLunKind,
  IscsiLunName,
  IscsiMissingLun,
  IscsiOwnership,
  IscsiOwnershipReason,
  IscsiOwnershipTag,
  IscsiPortal,
  IscsiPortalAddress,
  IscsiPortalRequest,
  IscsiPortalWithoutInterface,
  IscsiQueryFlag,
  IscsiSession,
  IscsiSessionConnection,
  IscsiSessionList,
  IscsiStubLun,
  IscsiTargetDetail,
  IscsiTargetList,
  IscsiTargetName,
  IscsiTargetSecurity,
  IscsiTargetServingNothing,
  IscsiTargetStateRequest,
  IscsiTargetSummary,
  lunGrowGuidance,
  unbracketAddress,
  UpdateIscsiLunRequest,
  UpdateIscsiTargetRequest,
  ZVOL_PATH_PREFIX,
  zvolDatasetFromPath,
  zvolDevicePath,
} from './schemas/iscsi.js'

// Job schemas
export {
  Job,
  JobAccepted,
  JobDetail,
  JobList,
  JobRef,
  JobStatus,
} from './schemas/jobs.js'

// Mount schemas (Epic 18 — external & local storage)
export {
  CreateMountRequest,
  DeleteMountQuery,
  MountCapacity,
  MountCharset,
  MountCifsCache,
  MountCifsOptions,
  MountCifsSec,
  MountCommonOptions,
  MountCredentials,
  MountCredentialsInfo,
  MountDetail,
  MountEntry,
  MountHealth,
  MountInlineCredentials,
  MountKind,
  MountLookupCache,
  MountMode,
  MountNfsOptions,
  MountNfsProto,
  MountNfsSec,
  MountOptions,
  MountQueryFlag,
  MountRequestOptions,
  MountSec,
  MountState,
  MountStateRequest,
  MountSummary,
  MountTestRequest,
  MountTestResult,
  MountTestVerdict,
  MountType,
  MountUnit,
  MountVers,
  UpdateMountRequest,
} from './schemas/mounts.js'

// Replication schemas (Epic 5.5)
export {
  LenientReplicationTask,
  RemotesFile,
  RemoteTestResult,
  ReplicatePlan,
  ReplicatePlanRequest,
  ReplicateRequest,
  ReplicationLocation,
  ReplicationRemote,
  ReplicationTarget,
  ReplicationTask,
  ReplicationTaskName,
  ReplicationTaskStatus,
  UpsertRemoteRequest,
} from './schemas/replication.js'

// Schedule schemas (Epic 17 — uniform ANAS-owned snapshot schedules)
export {
  LastScrub,
  PeriodicScrubState,
  RetentionBucket,
  RetentionPlan,
  RetentionPolicy,
  ScheduledSnapshot,
  ScheduleId,
  ScheduleRunResult,
  ScrubMechanism,
  ScrubRunning,
  ScrubTarget,
  ScrubToggleRequest,
  SnapshotCadence,
  SnapshotSchedule,
  SnapshotScheduleDetail,
  SnapshotScheduleRunResult,
  SnapshotScheduleStatus,
  SnapshotSource,
  SnapshotTarget,
} from './schemas/schedules.js'

// Share schemas (SMB + NFS)
export {
  CreateNfsExportRequest,
  CreateSmbShareRequest,
  NfsClient,
  NfsExport,
  ShareEntry,
  SmbConnection,
  SmbGlobalConfig,
  SmbShare,
  SmbShareDetail,
  UpdateNfsExportRequest,
  UpdateSmbGlobalConfigRequest,
  UpdateSmbShareRequest,
} from './schemas/shares.js'

// Snapshot schemas
export {
  CloneSnapshotRequest,
  CreateSnapshotRequest,
  RenameSnapshotRequest,
  Snapshot,
} from './schemas/snapshots.js'

// ZFS schemas
export {
  AddVdevRequest,
  AttachDiskRequest,
  CreatePoolRequest,
  ExpansionBusyState,
  ExpansionCapability,
  ExpansionGateReason,
  ExpansionOpKind,
  ExpansionTarget,
  ExportPoolRequest,
  ImportPoolRequest,
  PoolDetail,
  PoolDisk,
  PoolExpansionReport,
  PoolHealthMessage,
  PoolMountpointRequest,
  PoolProperties,
  PoolState,
  PoolSummary,
  PveStorageRef,
  ScanFunction,
  ScanState,
  ScanStatus,
  ScrubRequest,
  TrimPoolRequest,
  UpdatePoolPropertiesRequest,
  Vdev,
  VdevGroup,
  VdevRole,
  VdevSpec,
  VdevState,
  VdevType,
} from './schemas/zfs.js'
